apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-0
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches the PVCs
  hostPath:
    path: "/mnt/data0"  # Adjust this path as needed for your environment

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches the PVCs
  hostPath:
    path: "/mnt/data1"  # Adjust this path as needed for your environment

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches the PVCs
  hostPath:
    path: "/mnt/data2"  # Adjust this path as needed for your environment
