apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Replace with your storage class name
  hostPath:
    path: /mnt/data-elasticsearch-0  # Replace with your actual host path for pod elasticsearch-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Replace with your storage class name
  hostPath:
    path: /mnt/data-elasticsearch-1  # Replace with your actual host path for pod elasticsearch-master-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Replace with your storage class name
  hostPath:
    path: /mnt/data-elasticsearch-2  # Replace with your actual host path for pod elasticsearch-master-2
